# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 07:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('religos', '0003_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='name',
            field=models.CharField(default='dummy', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='img',
            field=models.ImageField(upload_to='ocrimg'),
        ),
        migrations.AlterField(
            model_name='place',
            name='add_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
