# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-17 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('religos', '0004_auto_20170117_0752'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='img',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='name',
        ),
        migrations.AddField(
            model_name='photo',
            name='file',
            field=models.FileField(default='dummy', upload_to='photos/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
