# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('religos', '0006_photo_ocr_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='add_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
