# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-21 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('religos', '0007_auto_20170121_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='place',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
